### PR TITLE
Add cluster wsgi setting information

### PR DESCRIPTION
**Pull request by yencli**

### CODE REVIEW

**Comment by rezib** [comment]
Why not setting it directly in the Apache configuration file provided by slurm-web directly: https://github.com/edf-hpc/slurm-web/blob/master/conf/slurm-web-restapi.conf ?

**Comment by yencli** [comment]
There you go

**Comment by rezib** [comment]
As required by the contributing guidelines, please explain in commit message why you are doing this change.

**Comment by rezib** [comment]
Thanks for the modifications, it's been merged.

**Pull request closed without merging**
