### PR TITLE
Shortening the static file loading interval

### PR DESCRIPTION
**Pull request by yencli**

### CODE REVIEW

**Comment by rezib** [comment]
Can you please explain what are trying to fix with this commit and why this is supposed to fix it?

**Comment by rezib** [comment]
Can you explain are you also modifying the `SECRET_KEY` in this commit as well?

**Comment by yencli** [comment]
SECRET_KEY is not modified but refactorized.

**Comment by rezib** [comment]
I would have expected removed code with a refactorization but your commit only adds new code.

**Comment by rezib** [comment]
Why 600 seconds instead of 0? Setting a value of 0 would have fixed #99 but here we are just lowering the effect. A value of 600 does not actually solve the admin experience issue...

**Pull request closed without merging**
