### PR TITLE
Add RHEL7 spec file

### PR DESCRIPTION
**Pull request by AaronTHolt**
I've managed to get slurm-web running on RHEL7. For the moment it takes a bit of work to get it running. Hopefully future releases can fix this. Perhaps this should be in a separate branch instead of creating a new directory? I'm not sure if a adding a new directory will break the debian build or not.

I've run into some problems and would appreciate someone with RHEL and rpm knowledge to look over/fix things:
1. Many of the required packages aren't in the yum rpm database (pyslurm, jquery-flot, bootstrap). Thus even after they're installed, yum still doesn't recognize them. As they are in the required package section, the only way to build is with the rpm --nodeps option. Is there a good way to list a required package not in the rpm database? For now installing with the --nodeps option works.
2. SElinux on RHEL7 prevents apache from accessing files it needs (like jquery, SLURM shared objects, and a few others). Ideally, an SElinux policy to fix this would somehow be installed with slurm-web. I'm not sure how to go about this as the files SElinex blocks could be in different places. For now, SElinux either needs to be disabled or a custom policy needs to be built.
3. For whatever reason I can't get the rpm to build without both a tar.gz and an uncompressed version of slurm-web in the SOURCES directory. Perhaps someone knows how to fix this?
4. Rpms typically have a format of name-version-release.architecture.rpm.  For this reason packages with a "-" are frowned upon. Perhaps rename slurm-web to SlurmWeb or slurm_web? I suppose only the rpm needs be renamed. 
5. Ideally you could just "rpm -ivh slurm-web.rpm" and the whole thing would install. Currently you have to do three separate "rpm -ivh" commands (See install instructions below). How do you install the whole package with one command? 

Install instructions:
1. Install dependencies <a href="http://edf-hpc.github.io/slurm-web/installation.html"> listed here </a>
2. <a href="http://wiki.centos.org/HowTos/SetupRpmBuildEnvironment"> Create an rpm build environment </a> 
3. Copy the spec file to the SPECS directory
4. Copy the slurm-web directory to the SOURCES directory
5. Create a tar.gz in the SOURCES directory as well
    your directory structure should look like:
/rpmbuild/
----SPECS/
--------slurm-web.spec
----SOURCES/
--------slurm-web
--------slurm-web.tar.gz
----RPMS/
----SRPMS/
----BUILD/
----BUILDROOT/
6. in the SPECS directory, build the rpms:
        $rpmbuild -ba slurm-web.spec
7. Install the rpms (they will have a version in the name like slurm-web-restapi-1.1.3-1.el7.noarch.rpm)
        $rpm -ivh --nodeps slurm-web-restapi
        $rpm -ivh --nodeps slurm-web-dashboard
        $rpm -ivh --nodeps slurm-web
8. Configure apache and disable SElinux (or make a custom policy)

### CODE REVIEW

**Comment by rezib** [comment]
Hi Aaron,

Thank you very much for your great work on this! :)

The new directory at the root of the project won't break the debian build, no worry. But I would have named it `rpm` instead of `RHEL7`. Since there shouldn't be much differences between all RPM based distributions (hopefully), we can manage those with conditionals statements inside a unique spec file if needed. What do you think?

Trying to add bits to your points:

1/ For the missing deps in RHEL/EPEL:
- pyslurm: I guess we could work a bit with @gingergeeks to improve this quite easily, at least to get a working spec file.
- jquery-flot: The current usage of flot in slurm-web is quite limited (just a few simple pie charts). Maybe we can find an alternative that's more generally available to RHEL/EPEL users? Do you know any lib that could be a better choice?
- bootstrap: That's quite sad indeed since bootstrap is quite common these days...

4/ A quick look to EPEL shows that many packages have a dash in their names, are you sure about your statement?

**Comment by anderbubble** [comment]
Further to rezib's comment, minus (-) in rpm names are fine. RPMs are not *named* name-version-release.architecture.rpm in the metadata sense. The filename isn't particularly important, and having (-) characters in the name field is fine and common (and certainly preferred over CamelCase or underscores).

I'm working to build the rpm in my own environment, just to verify/test. More comments forthcoming.

**Comment by anderbubble** [comment]
Also, I think it'd be good to either work to package any missing dependencies, or even to try to get them into epel. (Bootstrap is a notable example that I think should be in epel.)

**Comment by anderbubble** [comment]
rezib,

Though RHEL7 is probably too specific, I think redhat is a reasonable location for a specfile... unless you want to rename the "debian" directory to "deb" ;)

**Comment by mehdid** [comment]
Usually, spec files are found in top directory. Why should we put it inside a specific subdir here?

FWIW, The "debian" is part of the debian package specification. Not a choice of ours.

**Comment by anderbubble** [comment]
I've made some changes with respect to comments here.

anderbubble/slurm-web@365ec898832ba460c761c68c606e4abd43fd5ec4

* I moved the specfile out to the base / top directory
* I removed extraneous whitespace :)
* I configured the specfile to decompress the source tarball as part of the build (%setup macro)

In this state, I was able to build the rpms with the following steps:

* put spec file in SPECS
* put source tarball in SOURCES
* rpmbuild -ba slurm-web.spec

Regarding installation of multiple rpms, it's entirely normal to have to install multiple packages. Yum would take care of this automatically if all three of these packages were in a yum repository. Otherwise, you can do

  rpm -i slurm-web{,-restapi,-dashboard}*.rpm

**Comment by datakid** [comment]
I can't get this to work yet. First problem was the version number. I had just checked out from head, so I had no idea. I changed line 44 to remove the ```-%{slurm_web_ver}``` and that solved one problem.

Then I get a missing slurm-dashboard.js:

```
+ install -m644 js/slurm-dashboard.js /root/rpmbuild/BUILDROOT/slurm-web-2.0-1.el7.centos.x86_64/usr/share/slurm-web/dashboard/js/slurm-dashboard.js
install: cannot stat 'js/slurm-dashboard.js': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.fBo9XQ (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.fBo9XQ (%install)
```
Where do I find slurm-dashboard.js?

**Comment by datakid** [comment]
If I comment out the two lines that refer to the non existent file, everything builds nicely. I have yet to install  though...

**Comment by rezib** [comment]
@datakid: slurm-dashboard.js used to contain all the JS code in slurm-web versions <=1.1. Starting from version 2.0.0, the JS code has been split among multiples JS files. The above spec file has to be updated to take this into consideration...

**Comment by datakid** [comment]
Ah! OK - how far back ion the commit history do I need to go?

**Comment by datakid** [comment]
So, slurm-dashboard.js was replaced by a bunch of things in the js/ folder in this commit 3d25307e9d4bf6a5c4928dc1278713ac03150247 

The new question I have is do I need to add them all, or can I glob them, or do I only need to add a few?

**Comment by datakid** [comment]
Here's the new spec file with the corrections necessary: 65ad8f94f58952a44158a3da02797511672bd6cc

**Comment by datakid** [comment]
ok. Centos users will need to ```yum install mod_wsgi``` if it's not already installed.

Also, it looks like the default deb apache2 user has been hard coded somewhere - I'm getting "user www-data not found" - in Centos this user is apache.

I [asked on SO](http://stackoverflow.com/questions/38236618/packaging-web-software-for-different-linux-distros) and it looks like it's not done. 

So I think something like this needs to happen:

either some sort of var is created and swapped in using something like:

`OS=`awk -F= '/^ID=/{print $2}' /etc/os-release`; if [ $OS == "debian" ]; then export APACHE_RUN_USER=www-data; else export APACHE_RUN_USER=apache; fi`

Of course, the only two files it happens in are conf files, not script files, so it's probably saner to add a new file, and adjust the spec file - create a ```slurm-web-restapi.rpm.conf```, make the appropriate changes, and adjuste the spec.

The RPMs don't build for me now because I've created new files, but I presume this is the best method. I'll try making the adjustment locally to see if it's sufficient. 

Ok, it looks like httpd has now started correctly. I can't see the site, but I presume I just need to hunt around.

**Comment by datakid** [comment]
Ok, that works a treat. My site is a big bunch of naught, but I presume that's because I've not done the other configurations required.

**Comment by rezib** [comment]
@datakid: hey let me first thank you for your work, that's awesome and really appreciated :+1:

**Comment by datakid** [comment]
Ok, I see the problem here. That spec file only puts the necessary web front endy bits in place. Nothing else is deployed.

Can you please:

- confirm that the requirements are correct (eg is nodejs now a req in slurm-web 2.0?)
- confirm, when debian installs slurm-web, which files go where. When I attempt to install the deb package on debian 8.5, there is a lot of stuff in /usr/share/slurm-web. In centos I have nothing in /etc/slurm-web except racks.xml for instance. I think there should be more in there.

**Comment by datakid** [comment]
similarly, there is no conf-server in /usr/share/slurm-web (for instance). I am discovering these by doing deep dives into the dirs - it's tedious.

ls  -la  debian/slurm-web
ls  -la debian/slurm-web-confdashboard
ls  -la debian/slurm-web-dashboard
ls  -la debian/slurm-web-restapi

**Comment by rezib** [comment]
>  confirm that the requirements are correct (eg is nodejs now a req in slurm-web 2.0?)

You can find all requirements in https://github.com/edf-hpc/slurm-web/blob/master/debian/control.

Slurm-web needs those to build:

* node-uglify,
* fonts-dejavu-core (or any valid TTF font of your choice)
* node-opentypejs (>> 0.4.3-1)

node-uglify and node-opentypejs depend on nodejs, so yes slurm-web indirectly depends on nodejs.

Then, slurm-web packages depend on those to install and run:

* libapache2-mod-wsgi
* python-flask
* python-pyslurm (>= 15.08)
* clustershell,
* python-ldap
* python-itsdangerous
* python-redis (optional)
* libjs-bootstrap
* libjs-jquery
* libjs-jquery-flot
* libjs-jquery-tablesorter
* libjs-requirejs
* libjs-requirejs-text
* libjs-three (>= 72)
* libjs-bootstrap-typeahead
* libjs-bootstrap-tagsinput
* libjs-d3
* libjs-handlebars
* libjs-async

>  confirm, when debian installs slurm-web, which files go where. When I attempt to install the deb package on debian 8.5, there is a lot of stuff in /usr/share/slurm-web. In centos I have nothing in /etc/slurm-web except racks.xml for instance. I think there should be more in there.

There are 3 deb packages, here is their content:

```
# dpkg -L slurm-web-restapi
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/slurm-web-restapi
/usr/share/doc/slurm-web-restapi/changelog.gz
/usr/share/doc/slurm-web-restapi/copyright
/usr/share/slurm-web
/usr/share/slurm-web/restapi
/usr/share/slurm-web/restapi/cors.py
/usr/share/slurm-web/restapi/mocks.py
/usr/share/slurm-web/restapi/templates
/usr/share/slurm-web/restapi/templates/proxy.html
/usr/share/slurm-web/restapi/schema
/usr/share/slurm-web/restapi/schema/dtd
/usr/share/slurm-web/restapi/schema/dtd/racks.dtd
/usr/share/slurm-web/restapi/cache.py
/usr/share/slurm-web/restapi/racks.py
/usr/share/slurm-web/restapi/mocks
/usr/share/slurm-web/restapi/mocks/nodes.json
/usr/share/slurm-web/restapi/mocks/topology.json
/usr/share/slurm-web/restapi/mocks/cluster.json
/usr/share/slurm-web/restapi/mocks/racks.json
/usr/share/slurm-web/restapi/mocks/partitions.json
/usr/share/slurm-web/restapi/mocks/qos.json
/usr/share/slurm-web/restapi/mocks/reservations.json
/usr/share/slurm-web/restapi/mocks/job.json
/usr/share/slurm-web/restapi/mocks/jobs.json
/usr/share/slurm-web/restapi/slurmrestapi.py
/usr/share/slurm-web/restapi/static
/usr/share/slurm-web/restapi/static/xdomain.min.js
/usr/share/slurm-web/restapi/requirements.txt
/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi
/usr/share/slurm-web/restapi/auth.py
/usr/share/slurm-web/restapi/settings.py
/etc
/etc/apache2
/etc/apache2/conf-available
/etc/apache2/conf-available/slurm-web-restapi.conf
/etc/slurm-web
/etc/slurm-web/restapi.conf
/etc/slurm-web/racks.xml
```

```
# dpkg -L slurm-web-dashboard
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/slurm-web-dashboard
/usr/share/doc/slurm-web-dashboard/changelog.gz
/usr/share/doc/slurm-web-dashboard/copyright
/usr/share/slurm-web
/usr/share/slurm-web/dashboard
/usr/share/slurm-web/dashboard/js
/usr/share/slurm-web/dashboard/js/fonts
/usr/share/slurm-web/dashboard/js/fonts/DejaVuSansMono.typeface.js
/usr/share/slurm-web/dashboard/js/modules
/usr/share/slurm-web/dashboard/js/modules/qos
/usr/share/slurm-web/dashboard/js/modules/qos/qos.hbs
/usr/share/slurm-web/dashboard/js/modules/qos/qos.js
/usr/share/slurm-web/dashboard/js/modules/racks
/usr/share/slurm-web/dashboard/js/modules/racks/racks.js
/usr/share/slurm-web/dashboard/js/modules/racks/racks.hbs
/usr/share/slurm-web/dashboard/js/modules/reservations
/usr/share/slurm-web/dashboard/js/modules/reservations/reservations.hbs
/usr/share/slurm-web/dashboard/js/modules/reservations/reservations.js
/usr/share/slurm-web/dashboard/js/modules/jobs-map
/usr/share/slurm-web/dashboard/js/modules/jobs-map/modal-node.hbs
/usr/share/slurm-web/dashboard/js/modules/jobs-map/modal-core.hbs
/usr/share/slurm-web/dashboard/js/modules/jobs-map/jobs-map.js
/usr/share/slurm-web/dashboard/js/modules/jobs-map/jobs-map.hbs
/usr/share/slurm-web/dashboard/js/modules/gantt
/usr/share/slurm-web/dashboard/js/modules/gantt/gantt.hbs
/usr/share/slurm-web/dashboard/js/modules/gantt/gantt-nodes.hbs
/usr/share/slurm-web/dashboard/js/modules/gantt/gantt.js
/usr/share/slurm-web/dashboard/js/modules/gantt/gantt-qos.hbs
/usr/share/slurm-web/dashboard/js/modules/topology
/usr/share/slurm-web/dashboard/js/modules/topology/topology.hbs
/usr/share/slurm-web/dashboard/js/modules/topology/topology.js
/usr/share/slurm-web/dashboard/js/modules/3d-view
/usr/share/slurm-web/dashboard/js/modules/3d-view/3d-view.js
/usr/share/slurm-web/dashboard/js/modules/3d-view/iframe.js
/usr/share/slurm-web/dashboard/js/modules/3d-view/3d-view.hbs
/usr/share/slurm-web/dashboard/js/modules/3d-view/camera
/usr/share/slurm-web/dashboard/js/modules/3d-view/camera/first-person-controls.js
/usr/share/slurm-web/dashboard/js/modules/3d-view/camera/pacman-auto.js
/usr/share/slurm-web/dashboard/js/modules/3d-view/camera/orbit-controls.js
/usr/share/slurm-web/dashboard/js/modules/partitions
/usr/share/slurm-web/dashboard/js/modules/partitions/partitions.hbs
/usr/share/slurm-web/dashboard/js/modules/partitions/partitions.js
/usr/share/slurm-web/dashboard/js/modules/jobs
/usr/share/slurm-web/dashboard/js/modules/jobs/jobs.js
/usr/share/slurm-web/dashboard/js/modules/jobs/jobs.hbs
/usr/share/slurm-web/dashboard/js/modules/jobs/table-jobs.hbs
/usr/share/slurm-web/dashboard/js/modules/jobs/modal-job.hbs
/usr/share/slurm-web/dashboard/js/helpers
/usr/share/slurm-web/dashboard/js/helpers/view.js
/usr/share/slurm-web/dashboard/js/helpers/boolean.js
/usr/share/slurm-web/dashboard/js/helpers/jobs.js
/usr/share/slurm-web/dashboard/js/helpers/array.js
/usr/share/slurm-web/dashboard/js/helpers/string.js
/usr/share/slurm-web/dashboard/js/helpers/different.js
/usr/share/slurm-web/dashboard/js/helpers/date.js
/usr/share/slurm-web/dashboard/js/helpers/number.js
/usr/share/slurm-web/dashboard/js/helpers/keycode.js
/usr/share/slurm-web/dashboard/js/utils
/usr/share/slurm-web/dashboard/js/utils/user.js
/usr/share/slurm-web/dashboard/js/utils/jobs.js
/usr/share/slurm-web/dashboard/js/utils/tagsinput.js
/usr/share/slurm-web/dashboard/js/utils/tablesorter.js
/usr/share/slurm-web/dashboard/js/utils/ajax.js
/usr/share/slurm-web/dashboard/js/utils/fakePlaceholder.js
/usr/share/slurm-web/dashboard/js/utils/token.js
/usr/share/slurm-web/dashboard/js/utils/date.js
/usr/share/slurm-web/dashboard/js/utils/topology.js
/usr/share/slurm-web/dashboard/js/utils/flot.js
/usr/share/slurm-web/dashboard/js/utils/page.js
/usr/share/slurm-web/dashboard/js/core
/usr/share/slurm-web/dashboard/js/core/navbar
/usr/share/slurm-web/dashboard/js/core/navbar/navbar.hbs
/usr/share/slurm-web/dashboard/js/core/navbar/navbar.js
/usr/share/slurm-web/dashboard/js/core/login
/usr/share/slurm-web/dashboard/js/core/login/login.js
/usr/share/slurm-web/dashboard/js/core/login/login.hbs
/usr/share/slurm-web/dashboard/js/core/clusters
/usr/share/slurm-web/dashboard/js/core/clusters/clusters.js
/usr/share/slurm-web/dashboard/js/core/clusters/clusters.hbs
/usr/share/slurm-web/dashboard/js/core/index.js
/usr/share/slurm-web/dashboard/js/libraries
/usr/share/slurm-web/dashboard/js/libraries/xdomain.min.js
/usr/share/slurm-web/dashboard/js/libraries/xdomain.js
/usr/share/slurm-web/dashboard/js/draw
/usr/share/slurm-web/dashboard/js/draw/3d-map.js
/usr/share/slurm-web/dashboard/js/draw/2d-legend.js
/usr/share/slurm-web/dashboard/js/draw/3d-draw.js
/usr/share/slurm-web/dashboard/js/draw/2d-draw.js
/usr/share/slurm-web/dashboard/js/draw/2d-intersections.js
/usr/share/slurm-web/dashboard/js/draw/factor.js
/usr/share/slurm-web/dashboard/js/draw/colors.js
/usr/share/slurm-web/dashboard/css
/usr/share/slurm-web/dashboard/css/dashboard.css
/usr/share/slurm-web/dashboard/static
/usr/share/slurm-web/dashboard/static/asc.gif
/usr/share/slurm-web/dashboard/static/logo-login.png
/usr/share/slurm-web/dashboard/static/wall.jpg
/usr/share/slurm-web/dashboard/static/logo.png
/usr/share/slurm-web/dashboard/static/bg.gif
/usr/share/slurm-web/dashboard/static/roof.jpg
/usr/share/slurm-web/dashboard/static/floor.jpg
/usr/share/slurm-web/dashboard/static/rack.jpg
/usr/share/slurm-web/dashboard/static/favicon.ico
/usr/share/slurm-web/dashboard/static/desc.gif
/usr/share/slurm-web/dashboard/index.html
/usr/share/slurm-web/dashboard/3d-view.html
/etc
/etc/apache2
/etc/apache2/conf-available
/etc/apache2/conf-available/slurm-web-dashboard.conf
```

```
admsrv@noeyyrx6:~$ dpkg -L slurm-web-confdashboard
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/slurm-web-confdashboard
/usr/share/doc/slurm-web-confdashboard/changelog.gz
/usr/share/doc/slurm-web-confdashboard/copyright
/usr/share/slurm-web
/usr/share/slurm-web/conf-server
/usr/share/slurm-web/conf-server/slurm-web-conf.wsgi
/usr/share/slurm-web/conf-server/slurmwebconf.py
/etc
/etc/apache2
/etc/apache2/conf-available
/etc/apache2/conf-available/slurm-web-confdashboard.conf
/etc/slurm-web
/etc/slurm-web/dashboard
/etc/slurm-web/dashboard/config.json
/etc/slurm-web/dashboard/topology.config.json
/etc/slurm-web/dashboard/clusters.config.js
/etc/slurm-web/dashboard/2d.config.json
/etc/slurm-web/dashboard/3d.colors.config.json
/etc/slurm-web/dashboard/3d.config.json
/etc/slurm-web/dashboard/2d.colors.config.json
```

You can basically ignore the content of `/usr/share/doc` that is generated at build time by debian packaging tools.

**Comment by datakid** [comment]
@rezib can you please explain the diff between dashboard and confdashboard?

**Comment by datakid** [comment]
I presume that this is still listed is a mistake, given that it no longer exists?

/usr/share/slurm-web/dashboard/js/helpers/view.js

**Comment by datakid** [comment]
also: 

/usr/share/slurm-web/dashboard/js/libraries/xdomain.min.js

(sorry, I'm working through this line by line)

**Comment by datakid** [comment]
also:
/usr/share/slurm-web/dashboard/js/fonts
/usr/share/slurm-web/dashboard/js/fonts/DejaVuSansMono.typeface.js

**Comment by datakid** [comment]
In restapi:

 - there is a restapi/static/xdomain.min.js which doesn't exist in either static or js/libraries/ ?
 - there is a reference to an entire missing directory:  /usr/share/slurm-web/restapi/mocks neither exists in the code base nor do any of the files it apparently contains?

**Comment by datakid** [comment]
New spec file added c15b437bb51b79833316d43941338c2da7b9683a

**Comment by rezib** [comment]
> @rezib can you please explain the diff between dashboard and confdashboard?

I'm realizing this point is not properly explained in the [architecture documentation](http://edf-hpc.github.io/slurm-web/architecture.html). I just opened #131 to fix this.

In a few words:

* dashboard is basically the JS+ HTML code of the dashboard
* confdashboard is a tiny python flask app to deliver the JSON conf files to the dashboard

> I presume that this is still listed is a mistake, given that it no longer exists?
> /usr/share/slurm-web/dashboard/js/helpers/view.js

Well, it does exist:
https://github.com/edf-hpc/slurm-web/blob/master/js/helpers/view.js
:blush:

> also:
> /usr/share/slurm-web/dashboard/js/libraries/xdomain.min.js
> (sorry, I'm working through this line by line)

The minified xdomain.min.js is generated at build time using `js/libraries/xdomain.js`, here:
https://github.com/edf-hpc/slurm-web/blob/master/debian/rules#L7

> also:
> /usr/share/slurm-web/dashboard/js/fonts
> /usr/share/slurm-web/dashboard/js/fonts/DejaVuSansMono.typeface.js

This file is a TTF font converted to a format valid for three.js library. It is generated at build time with a script provided in opentypejs package, here:
https://github.com/edf-hpc/slurm-web/blob/master/debian/rules#L9

> there is a reference to an entire missing directory: /usr/share/slurm-web/restapi/mocks neither exists in the code base nor do any of the files it apparently contains?

Forget about those files, they should not have never landed in the packages. They are not needed.

> New spec file added c15b437
> Hasn't been tested unfortunately - I've been doing this skunk works and I don't know how much more time I can spend on it :/

OK, thank you for keeping up the good work! I'll merge this once you're fine with it.

**Comment by kcgthb** [comment]
Hi there, 

I managed to build the RPMs with the following adjustment to the spec file:
``` 
diff --git a/slurm-web.spec b/slurm-web.spec
index dd282bf..9f2c80b 100644
--- a/slurm-web.spec
+++ b/slurm-web.spec
@@ -64,7 +64,7 @@ install -d $RPM_BUILD_ROOT/etc/slurm-web/dashboard
 install -m644 conf/slurm-web-confdashboard.conf $RPM_BUILD_ROOT/etc/slurm-web/slurm-web-confdashboard.conf
 install -m644 conf/dashboard/config.json $RPM_BUILD_ROOT/etc/slurm-web/dashboard/config.json
 install -m644 conf/dashboard/topology.config.json $RPM_BUILD_ROOT/etc/slurm-web/dashboard/topology.config.json
-install -m644 conf/dashboard/clusters.config.json $RPM_BUILD_ROOT/etc/slurm-web/dashboard/clusters.config.json
+install -m644 conf/dashboard/clusters.config.js $RPM_BUILD_ROOT/etc/slurm-web/dashboard/clusters.config.js
 install -m644 conf/dashboard/2d.config.json $RPM_BUILD_ROOT/etc/slurm-web/dashboard/2d.config.json
 install -m644 conf/dashboard/2d.colors.config.json $RPM_BUILD_ROOT/etc/slurm-web/dashboard/2d.colors.config.json
 install -m644 conf/dashboard/3d.config.json $RPM_BUILD_ROOT/etc/slurm-web/dashboard/3d.config.json
@@ -181,7 +181,7 @@ install -m644 rest/settings.py $RPM_BUILD_ROOT/usr/share/slurm-web/restapi/setti
 install -m644 rest/slurm-web-restapi.wsgi $RPM_BUILD_ROOT/usr/share/slurm-web/restapi/slurm-web-restapi.wsgi
 install -m644 rest/slurmrestapi.py $RPM_BUILD_ROOT/usr/share/slurm-web/restapi/slurmrestapi.py
 install -m644 rest/requirements.txt $RPM_BUILD_ROOT/usr/share/slurm-web/restapi/requirements.txt
-install -m644 schema/template/proxy.html $RPM_BUILD_ROOT/usr/share/slurm-web/restapi/templates/proxy.html
+install -m644 rest/templates/proxy.html $RPM_BUILD_ROOT/usr/share/slurm-web/restapi/templates/proxy.html
 install -m644 schema/racks.dtd $RPM_BUILD_ROOT/usr/share/slurm-web/restapi/schema/dtd/racks.dtd
```

**Comment by datakid** [comment]
Note to people following along at home: view.js has moved as of https://github.com/edf-hpc/slurm-web/commit/031a156228a180902cdaa896e881c207a5ce2a91

**Comment by datakid** [comment]
Ok, unfortunately this project hasn't been developed or refactored to be platform independent, which is understandable in a volunteer run project. But the work to be done to make it workable on rpm based distro is too much effort without a strong understanding of what it *should* look like.

I have put a final slurm-web.spec here f669b2c6c3be925b860f5fba3cc167bed7769166 

Currently this builds but doesn't actually work. If you comment out the python on line 206, it at least finishes installing, but the flask app isn't running.

**Comment by alexxxxx** [comment]
Hello,

I don't know if there is still interest in this pull request but just in case, please find below few comments. I know that this specfile is not targeting EPEL but getting inspired by their guideline[1] is a good start.

1) To get version evolving independently, it would be a good idea two have 2 specfiles.
2) +1 for getting python-<Package name> which is the convention for EPEL.
3) Pure python package should be installed under /usr/lib/python2.X/site-packages (macro %python_sitelib) and executable in /usr/bin using python entry point.
4) *.pyo and *pyc should be shipped with the RPM. Otherwise, yum remove won't get back to a clean state.
5) For operations like service restart, not in the %install section, make a post_install script for it.

For the point on where to store the specfile, in general I would say that it should be in an independent repo (another branch like maintainer is fine too).  If you want to keep it in the repo master branch, I like the direction collectd[2] took to put it in contrib directory.

[1]: https://fedoraproject.org/wiki/Packaging:Python
[2]: https://github.com/collectd/collectd/tree/master/contrib/redhat

**Pull request closed without merging**
